version: '3'

services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MAILER_SERVICE_URL=mailer-service:50051
    depends_on:
      - mailer-service

  mailer-service:
    build:
      context: .
      dockerfile: services/mailer-service/Dockerfile
    ports:
      - "50051:50051"
