version: '3'
# TODO: Add option to use a different ports
# TODO: Add option to use a different .ini file
services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "3080:3080"
    environment:
      - PORT=3080
      - MAILER_SERVICE_URL=mailer-service:50051
    depends_on:
      - mailer-service

  mailer-service:
    build:
      context: .
      dockerfile: services/mailer-service/Dockerfile
    ports:
      - "50051:50051"
